## Tablero Numérico
Este archivo crea la clase Base, la cual está compuesta de objetos que representan un tablero de buscaminas. Estos objetos cuentan con un atributo de filas, otro de columnas y un atributo tab. Este último se refiere a matrices compuestas de numeros enteros que toman valores en el rango [-1,8].

Cuando una componente de la matriz tiene el numero -1, representa una mina. Cuando toma numeros entre 0 y 8, representa el numero de minas vecinas a dicha casilla. 

El objeto Base contiene una matriz de las dimensiones especificadas por el usuario con un 10% de sus casillas como minas, ordenadas aleatoriamente. Para añadir el numero de minas vecinas a cada casilla, se debe aplicar el metodo vecinos_mina a un objeto de clase Base. La vecindad se define de forma horizontal, vertical y diagonal.

Finalmente, el método array_a_lista, convierte el atributo tab del objeto en una lista para facilitar su manejo.


In [2]:

import numpy as np
class Base:

    def __init__(self, cols = 10, filas = 10):
        
        self.cols = cols
        self.filas = filas
        
        # Porcentaje de minas del total de casillas
        p1 = 0.1
        minas = round((filas*cols)*p1)
        no_minas = filas*cols - minas
        
        # Ordenar minas y no minas en un array
        tab = np.array([0]*no_minas + [-1]*minas)
        
        # Reorganizar valores aleatoriamente en una matriz 
        # de las dimensiones indicaddas
        np.random.shuffle(tab)
        tab = np.reshape(tab, (filas, cols))
        
        # Atributo tab.
        self.tab = tab
        
    def __str__(self):
        return ("{0}".format(self.tab))
    
    def vecinos_mina(self):
        
        filas = self.filas
        cols = self.cols
        
        # Posibilidades de ubicaciones de vecinos: 
        # izquierda, arriba, abajo, derecha y sus posibles combinaciones.
        adjuntos = [(-1, 1), (0, 1), (1, 1), (-1, 0),
             (1, 0), (-1, -1), (0,-1), (1,-1)]
        
        # Matriz para adjuntar conteo de vecinos
        arr = np.zeros(shape = (filas, cols))
        for i in range(filas):
            for j in range(cols):
                for (di,dj) in adjuntos:
                    
                    # Evitar salir de los indices de la matriz
                    if 0 <= j + dj < filas and 0 <= i + di < cols:
                        # Dado que las minas se cuentan con un -1, 
                        # y las no-minas con 0, se restan los valores 
                        # de los vecinos.
                        arr[i,j] += -self.tab[i+di, j +dj]
                        
                # Añadir minas a la nueva matriz
                if self.tab[i,j] == -1:
                    arr[i,j] = self.tab[i,j]
                    
        self.tab = arr
        
    def array_a_lista(self):
        l = []
        for i in range(self.filas):
            for j in range(self.cols):
                l.append(self.tab[i][j])
        self.tab = l
        
t = Base()                    


In [3]:
print(t)

[[-1 -1  0  0  0  0  0 -1  0  0]
 [ 0  0  0  0  0  0  0 -1  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 -1  0]
 [ 0  0  0  0  0  0  0  0  0 -1]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 -1  0  0  0]
 [ 0 -1  0  0  0 -1  0  0  0  0]
 [ 0  0  0  0  0  0 -1  0  0  0]]


In [4]:
t.vecinos_mina()
print(t)

[[-1. -1.  1.  0.  0.  0.  2. -1.  2.  0.]
 [ 2.  2.  1.  0.  0.  0.  2. -1.  2.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  2.  2.  1.]
 [ 0.  0.  0.  0.  0.  0.  0.  1. -1.  2.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  2. -1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  1.  1.]
 [ 0.  0.  0.  0.  0.  1.  1.  1.  0.  0.]
 [ 1.  1.  1.  0.  1.  2. -1.  1.  0.  0.]
 [ 1. -1.  1.  0.  1. -1.  3.  2.  0.  0.]
 [ 1.  1.  1.  0.  1.  2. -1.  1.  0.  0.]]


In [6]:
import os
current_path = os.getcwd()
current_path

'C:\\Users\\Victoria\\Proyecto Programación'